version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/sre.conf:/etc/nginx/conf.d/default.conf
#    networks:
 #     - mynet
    network_mode: host
#    ports:
 #     - 80:80
  app:
    build: ./app
   # networks:
    #  - mynet
  #  ports:
   #   - 4567:4567
    network_mode: host
    container_name: sre-container
  sidecar:
    build: ./sidecar
    network_mode: host
    container_name: sidecar
networks:
  mynet: {}
